# Generated by Django 5.2.10 on 2026-01-18 19:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroceryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('purchased', models.BooleanField(default=False)),
                ('quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.RemoveField(
            model_name='grocerylist',
            name='family',
        ),
        migrations.RemoveField(
            model_name='groceryitems',
            name='grocery_list',
        ),
        migrations.RemoveField(
            model_name='groceryitems',
            name='product',
        ),
        migrations.DeleteModel(
            name='FamilyMember',
        ),
        migrations.DeleteModel(
            name='Family',
        ),
        migrations.DeleteModel(
            name='GroceryList',
        ),
        migrations.DeleteModel(
            name='GroceryItems',
        ),
        migrations.DeleteModel(
            name='Products',
        ),
    ]
