# Generated by Django 5.2.10 on 2026-01-18 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_groceryitem_remove_grocerylist_family_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groceryitem',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
