# Generated by Django 5.2.10 on 2026-01-18 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_groceryitem_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groceryitem',
            name='category',
            field=models.CharField(default='Other', max_length=100),
        ),
    ]
