# Generated by Django 5.2.10 on 2026-01-19 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_groceryitem_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groceryitem',
            options={'verbose_name': 'Grocery Item', 'verbose_name_plural': 'Grocery Items'},
        ),
        migrations.AlterField(
            model_name='groceryitem',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
